### ISSUE TITLE
got compiling error

### ISSUE THREAD

**Issue by sinyo-matu** [ymgyt/tracing-cloudwatch#36] opened 2024-03-24 15:03 UTC
Hi! Thank you for building this library.
This is my first time to use it.
But I got below error when compiling.

```sh
error[E0275]: overflow evaluating the requirement `&tempfile::file::NamedTempFile<_>: std::io::Write`
  --> /Users/*/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-cloudwatch-0.1.5/src/layer.rs:35:26
   |
35 |         CloudWatchLayer::new(Arc::new(NoopDispatcher::new()))
   |                          ^^^
   |
   = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`tracing_cloudwatch`)
   = note: required for `&tempfile::file::NamedTempFile<tempfile::file::NamedTempFile<_>>` to implement `std::io::Write`
   = note: 125 redundant requirements hidden
   = note: required for `&NamedTempFile<NamedTempFile<NamedTempFile<NamedTempFile<NamedTempFile<NamedTempFile<NamedTempFile<NamedTempFile<NamedTempFile<NamedTempFile<NamedTempFile<NamedTempFile<...>>>>>>>>>>>>` to implement `std::io::Write`
   = note: the full type name has been written to '/Users/*/target/debug/deps/tracing_cloudwatch-cbb3f9210321ab3a.long-type-5561743559099399737.txt'
   = note: required for `Arc<NamedTempFile<NamedTempFile<NamedTempFile<NamedTempFile<NamedTempFile<NamedTempFile<NamedTempFile<NamedTempFile<NamedTempFile<NamedTempFile<NamedTempFile<...>>>>>>>>>>>>` to implement `for<'writer> MakeWriter<'writer>`
   = note: the full type name has been written to '/Users/*/target/debug/deps/tracing_cloudwatch-cbb3f9210321ab3a.long-type-11439770948471775500.txt'
note: required by a bound in `CloudWatchLayer<S, D>`
  --> /Users/*/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-cloudwatch-0.1.5/src/layer.rs:43:13
   |
43 |     Arc<D>: for<'writer> MakeWriter<'writer>,
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `CloudWatchLayer<S, D>`

For more information about this error, try `rustc --explain E0275`.
error: could not compile `tracing-cloudwatch` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

toolchain:
stable-aarch64-apple-darwin (default)
rustc 1.77.0 (aedd173a2 2024-03-17)

**Comment by ymgyt** [comment] 2024-03-24 15:21
Thank you for reporting the issue. I were unable to reproduce it with the reported toolchain(`stable-aarch64-apple-darwin` with rustc 1.77.0), so could you provide some more information to help us reproduce it? 
It would be helpful if you could share the code that caused the compile error and the dependencies in your Cargo.toml.

**Comment by sinyo-matu** [comment] 2024-03-25 01:46
Actually It DO NOT reproduce on a brand new repo too.
This repo includes my Cargo.toml and the tracing setup part codes.
https://github.com/sinyo-matu/tracing-cloudwatch-repro

**Comment by ymgyt** [comment] 2024-03-25 05:09
thank you for creating repository. 
Inside the `tracing_cloudwatch::layer().with_client()` process, tokio::spawn() is being executed. 
https://github.com/ymgyt/tracing-cloudwatch/blob/14228194fdd355d1156e4ffa2200740ba90a6653/src/dispatch.rs#L44

Therefore, this process needs to be called after the tokio runtime has been entered.

```rust
fn main() {
    tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()
        .unwrap()
        .block_on(async {
            let subscriber = get_subscriber("test".into(), "info".into(), std::io::stdout);
            init_subscriber(subscriber);
            info!("Hello world!")
        });
```

**Comment by sinyo-matu** [comment] 2024-03-26 05:15
@ymgyt 
wow didn't know about that!
but it does not solve the issue.
compiling error is still there.

I aware of that the error is produced immediately after I add `tracing-cloudwatch` to the dependency field.
Maybe it is not about how I use it in my code.

**Comment by ymgyt** [comment] 2024-03-26 05:23
@sinyo-matu 

> I aware of that the error is produced immediately after I add tracing-cloudwatch to the dependency field.
Maybe it is not about how I use it in my code.

Thank you for the information.
Hmm, I'll continue to investigate. It would be helpful if you could provide the code that reproduces the error.

**Comment by sinyo-matu** [comment] 2024-03-26 06:49
@ymgyt 
Sure I'm working on it

**Comment by ymgyt** [comment] 2024-05-12 09:41
I close it but feel free to reopen

**Closed as completed by ymgyt** 2024-05-12 09:41 UTC
Labels: bug
